name: Scala 3 Migration Course CI

on:
  push:
    tags: '*'
    paths-ignore:
      - 'README.md'
      - '**/README.md'
      - 'bin/**'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'README.md'
      - '**/README.md'
      - 'bin/**'
    branches: [ main ]

  workflow_dispatch:

jobs:
  list-exercises:
    runs-on: ubuntu-latest
    outputs:
      exercises: ${{steps.list.outputs.exercises}}
    steps:
      - uses: actions/checkout@v3
      - id: list
        run: echo "::set-output name=exercises::$(ls ./exercises | grep exercise_ | jq -cnR '[inputs | select(length>0)]')"

  test-exercise:
    runs-on: ubuntu-latest
    needs: list-exercises
    strategy:
      fail-fast: false
      matrix:
        exercise: ${{fromJson(needs.list-exercises.outputs.exercises)}}
    name: Test ${{matrix.exercise}} 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        cache: 'sbt'
        distribution: 'temurin'

    - name: Test with sbt
      run: sbt test
      working-directory: ./exercises/${{matrix.exercise}}
  create_release:
    runs-on: ubuntu-latest
    needs: [test-exercise]
    # Release gets triggered only on creating new tags
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    name: Release ${{ github.ref }}

    steps:
      - name: Checkout Course Repo
        uses: actions/checkout@v3
        with:
          path: ${{ env.THIS_REPO }}
          fetch-depth: 0          

      - name: Set up Coursier
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:11

      - name: Setup Course Management Tools  
        run: |
          cs install --contrib cmta

      - name: Setup Coursier Cache
        uses: coursier/cache-action@v6.2
        with:
          root: ${{ env.THIS_REPO }}

      - name: Studentify Repo
        run: |
          mkdir -p studentified
          export PATH=${PATH}:$GITHUB_WORKSPACE/CMT/bin
          git config --global user.email "no-reply@epfl.ch"
          git config --global user.name "EPFL user"
          cmta studentify -f -g -m ${{ env.THIS_REPO }} -d studentified
          (cd studentified && exec zip -r ${{ env.THIS_REPO }}-student.zip ${{ env.THIS_REPO }})  
          
      - name: Linearize Repo
        run: |
          mkdir -p linearized
          cmta linearize -f -m ${{ env.THIS_REPO }} -d linearized
          mv linearized/${{ env.THIS_REPO }} linearized/${{ env.THIS_REPO }}-linearized
          (cd linearized && exec zip -r ${{ env.THIS_REPO }}-linearized.zip ${{ env.THIS_REPO }}-linearized)
        
      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: Upload Studentified repo to Github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # release created from previous step
          asset_path: ./studentified/${{ env.THIS_REPO }}-student.zip
          asset_name: ${{ env.THIS_REPO }}-student.zip
          asset_content_type: application/zip
     
      - name: Upload Linearized repo to Github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # release created from previous step
          asset_path: ./linearized/${{ env.THIS_REPO }}-linearized.zip
          asset_name: ${{ env.THIS_REPO }}-linearized.zip
          asset_content_type: application/zip
